!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons2
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5

' https://devicon.dev/
!includeurl DEVICONS/debian.puml
!includeurl DEVICONS/linux.puml
!includeurl DEVICONS/php.puml
!includeurl DEVICONS/postgresql.puml

' https://fontawesome.com/v5.0/icons?d=gallery&q=user&m=free
!includeurl FONTAWESOME/server.puml
!includeurl FONTAWESOME/envelope.puml
!includeurl FONTAWESOME/users.puml
!includeurl FONTAWESOME/chalkboard_teacher.puml
!includeurl FONTAWESOME/user_cog.puml
!includeurl FONTAWESOME/user_tie.puml

!if %variable_exists("RELATIVE_INCLUDE")
  !include %get_variable_value("RELATIVE_INCLUDE")/EXTRA/siutoba.puml
!else
  !includeurl https://raw.githubusercontent.com/maurom/C4-PlantUML/master/EXTRA/siutoba.puml
!endif
